### ISSUE TITLE
Big images just removing 200?

### ISSUE THREAD

**Issue by HristoBuyukliev** [zhivkopetrov/robotics_v1_entry#1]
Hi, so small images have eyes in the input images; and the output images, as described, are the input images, with eyes corrected by 150. 

However, the big images:
1. don't contain eyes
2. Can be trivially fixed, by just reducing each red pixel with value of over 200 by 150. 

The code below works for all the test images:

```
def correct_200(image_in, image_out):
    image_in[image_in >= 200] = image_in[image_in >= 200] - 150
    if (image_in == image_out).all():
        print('correctly removed red eyes!')
    else:
        print('there was some discrepancy :(')
        
for image_in, image_out in zip(input_images, output_images):
    np_image_in = convert_to_numpy(image_in)
    np_image_out = convert_to_numpy(image_out)
    correct_200(np_image_in, np_image_out)
```

**Comment by zhivkopetrov** [comment]
Hey, @HristoBuyukliev,

Thank you for opening an issue.
So there are two differrent issues you are reffering to and I will split them.

_big images don't contain eyes_
There is always a possibility that I've made an error when the test data was being generated.
If that is the case - I apologise for the inconvenience.

I got the same issue raised yesterday by another candidate.
I've then checked the big test case again (at least the first image) and it seemed everything was OK.

**I would like to know how you came to the conclusion that big images don't contain eyes?**
The earlier mentioned candidate from yesterday had build a small tool that visualized the test data images,
Indeed in the big test case there were no clear "red eyes".

However, I would like to stress out that a high red component value does not guarantee a red color.
For example
r = 255, g = 255, b = 255 produces a white color.
r = 255, g = 0, b = 255 produces a purple color.

**Comment by zhivkopetrov** [comment]
@HristoBuyukliev 
The second issue you've mentioned:
_Big images can be trivially fixed, by just reducing each red pixel with value of over 200 by 150._

This is correct. I've decided to use a red component value lower that 200 for the non-eye pixels not to obfuscate the task additionally.
However, if you submit the above posted "trivial solution" as your final submission this is what kind of evaluation you will get from my side:
(+) Bonus points from analyzing the data and uzing it to your advantage
(-) Negative points on not providing a generic solution, which does not follow the task description.
Only pixels, which are part of a eye pattern should have a red-eye component reduction.
Otherwise if I apply you algorithm to a real image - it will also reduce all red pixels with high values, even if they are not parts of eyes.

Cheers

**Comment by HristoBuyukliev** [comment]
@zhivkopetrov  Thanks for replying. I had understood the task wrongly, that we only needed to look at the red channel of the images. That did work for the small test case, but doesn't for the big one. 

However, for the first image in the big test case, I really can't see the red eyes. Can you define what you count as "red"?

Here is the first small image, where I can see the eyes:
![image](https://user-images.githubusercontent.com/6619799/187859329-486572d5-fe2e-40c4-b42c-cc4abb7fc176.png)

And here is the first big image, (a slice of it where there is a difference), and I really can't see anything. 

![image](https://user-images.githubusercontent.com/6619799/187860983-3a106a27-4c34-4537-b08b-8b186d580343.png)

**Comment by zhivkopetrov** [comment]
Hey, @HristoBuyukliev,

Thank you for the detailed explanation.

First to answer your question:
_Can you define what you count as "red"_
The criteria, which should be satisfied are described in the task description document.
Quoting from there:
**An occurrence of a red eye could be found in an image when all of the below criteria are satisfied:
- All non-whitespace characters found in one of the provided “eye patterns” could be mapped to the
existing image
- All mapped non-whitespace pixel values should have a red-component >= 200**

Now, about the missing red eyes in the big images:
I can not be certain how you are generating the data and how matplotlib visualizes the data.
Are you sure, you've parsed the data correctly?
Are you sure you've not swapped rows and columns?

I am attaching a visualization of mine of the big image.
Both the whole image and a cropped version of the eye pattern.
The image has a resolution of 640х360.
![o_big_image0 txt_converted_super_red](https://user-images.githubusercontent.com/25132160/187872689-98456e74-a363-4209-8bee-cf9ff7bdecc4.png)
![PXL_20220901_083529664 MP](https://user-images.githubusercontent.com/25132160/187872708-f91b36d1-3bf7-48df-9e67-be7c7a04794f.jpg)

Try printing only the red-component of the first image. Print a 5x5 square starting from rowIndex = 149 and colIndex = 295

**Comment by HristoBuyukliev** [comment]
You're absolutely right. I swapped the dimension order. Thanks again.

**Comment by zhivkopetrov** [comment]
Awesome! 
I am glad that you've managed to resolve the issue :)
